# Generated by Django 4.2 on 2023-04-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epojapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='home_adress',
        ),
        migrations.AddField(
            model_name='client',
            name='insurance',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='HomeAdress',
        ),
        migrations.AddField(
            model_name='client',
            name='insurance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='epojapp.insurancetype'),
        ),
    ]
