# Generated by Django 4.2 on 2023-04-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epojapp', '0003_uzivatel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=30, verbose_name='Tagy')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagy',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.CharField(max_length=200, verbose_name='Jméno a příjmení klienta'),
        ),
        migrations.AlterField(
            model_name='client',
            name='insurance',
            field=models.CharField(default='', max_length=200, verbose_name='Pojišťovna'),
        ),
        migrations.AlterField(
            model_name='client',
            name='insurance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='epojapp.insurancetype', verbose_name='Typ pojištění'),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(to='epojapp.tag'),
        ),
    ]
